
FEATURES: USE LIBRARIES!

- Have two modes:
---- Competition mode: you set a pace, and then the program makes the rhythm of all the songs go at that pace.

---- Your own pace mode: the program follows your pace, and makes the songs go at your pace
-> It knows the pace because you have a "giro" sensor on your phone and it detects by changes in directions.

But for this project I will do it with the spacebar, and the rhythm you click the spacebar marks the rhythm of the song.


I want a third mode,  called push your limits, where you indicate with one of your five fingers the level  you want it to go at: https://www.youtube.com/watch?v=p5Z_GGRCI5s HERE IS HOW YOU DO IT

Graphics: I want to have background black, add gif of NCS that goes to the rhythm of the song. Each gif is of different color for each level



Bro: incredible idea: add a multiplayer, so that you can race / run with other people live, in the same time. So you both connect, and then you both run to the same song.



* ESSENTIAL HINTS
***** Make sure you use OOP

I can make an object for a playlist
And have each song be an object

This allows you to modify aspets or characteristics super easily, just changing once in a class.




***** Planning / Schedule
Start planning how you're going to organize your code.

_Now_: get functionality working (don't worry about how it looks)

_Algorithmic research_:
Cite pages with pseudo-code (not real code, because you won't get credit for it)
Figure out what algorithm you need to use. (e.g. maze creating algorithm for pac-man)
IDEA: algorithm to determine the bpm of the rhythm of space bar clicking.

_Algorithmic complexity_:
Be careful about efficiency.

_Graphics_:
AFTER getting all of it working, you start working on making it beautiful and professional/product/professional looking.


***** Code organization
Main file to run the main animation (import all other files into this file)
Major classes in their own file
Big modes in their own file
General helper functions / baby modes in one file

Keep good style and good comments to not get lost
****** How to import a file
*Have all the files in the same folder*

import filename

_If you want to use a function from the file, then you do:_
filename.function_Name()

To avoid using this, you can do:
from filename import *
function_Name()

****** GIT

